### ISSUE TITLE
Validation timeout for Paris' GBFS

### ISSUE THREAD

**Issue by AntoineAugusti** [MobilityData/gbfs-validator#55]
When trying to validate the GBFS at https://velib-metropole-opendata.smoove.pro/opendata/Velib_Metropole/gbfs.json, I get a timeout error on the website.

```
{ "errorMessage": "2021-11-03T10:46:57.077Z fcd0740d-998f-4b3c-b45e-da4fb7e0553a Task timed out after 10.01 seconds" }
```

Validating this GBFS locally takes 19 seconds
```
time node cli.js https://velib-metropole-opendata.smoove.pro/opendata/Velib_Metropole/gbfs.json
```

it seems like the server is not slow to send responses, maybe a good opportunity to tackle performance improvements?

**Comment by AntoineAugusti** [comment]
Got a timeout on another feed/another version https://github.com/MobilityData/gbfs-validator/issues/74#issuecomment-1137215378

This time server responses are not very slow it seems

**Comment by PierrickP** [comment]
I dug a bit on it but didn't found.
I need to check again. It's probably a server detection (like on user-agent).

**Comment by AntoineAugusti** [comment]
@PierrickP Can you confirm that this is for the Clermont-Ferrand feed? I could get in touch with them to clarify things.

**Comment by PierrickP** [comment]
Hello @AntoineAugusti 

For **Velib** feed, the problem is only on the slowness of Velib feed (very variable, sometime more than 10sec) and the limitation on netlify functions.
It's limited to 10sec. It may be possible to increase on contacting customer support (@isabelle-dr see https://answers.netlify.com/t/function-timeout-increase/53881/2) 

For **Clermont-Ferrand**, there is an _error_ on their feed.
All URLs on the GBFS use HTTP, but if you curl on it, no answer. Only HTTP**S** exist. We can be mistaken by our browser, whose redirect automatically 
I think, we must _not_ do something on the validator. If you are in touch with them, can you ask them to fix it ?

++

**Comment by AntoineAugusti** [comment]
Thanks @PierrickP,  missed the HTTP link! We'll circle back with them.

**Comment by josee-sabourin** [comment]
@all-contributors please add @AntoineAugusti for bug

**Comment by richfab** [comment]
According to the [Velib website](https://www.velib-metropole.fr/donnees-open-data-gbfs-du-service-velib-metropole), the new feed URL as of September 26th, 2023 is:
https://velib-metropole-opendata.smovengo.cloud/opendata/Velib_Metropole/gbfs.json

This new URL is quicker so it can be validated by the gbfs-validator:
<img width="1283" alt="image" src="https://github.com/MobilityData/gbfs-validator/assets/2423604/481ca83c-b7da-4e25-9bc9-ccbaa65753e2">

The URL will be updated in systems.csv in https://github.com/MobilityData/gbfs/pull/580.

Additional note: The Netlify timeout was increased to the maximum (26 sec) on July 13th, 2023.
