### ISSUE TITLE
Error "can not require"

### ISSUE THREAD

**Issue by AntoineAugusti** [MobilityData/gbfs-validator#80]
When validating `https://vannes-gbfs.klervi.net/gbfs/2/gbfs.json` we get this error message.

Example: https://gbfs-validator.netlify.app/?url=https%3A%2F%2Fvannes-gbfs.klervi.net%2Fgbfs%2F2%2Fgbfs.json

**Comment by PierrickP** [comment]
Ok, multiple errors.

The feed is invalid. The `version` is missing on the `gbfs.json` file.

The validator attempt to validate on `v1.0` (because no version).
And try to validate `gbfs_versions` file. This file should be exists on `v1.0`, #81 fix that.

If you force the `v2.3`, an error from the schema is returned. I ll made another PR with the latest schemas (https://github.com/MobilityData/gbfs-json-schema/commit/5ac5522e029356b10c4b35972eb84f6499ed60d2)
